### ISSUE TITLE
运行起来这里报错是遇到过的问题吗

### ISSUE THREAD

**Issue by hjqiaho** [Launcher3-dev/Launcher3#24]
2022-08-31 18:47:36.981 5446-5446/com.android.launcher3 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.android.launcher3, PID: 5446
    java.lang.NoSuchMethodError: No interface method getMaximumWindowMetrics()Landroid/view/WindowMetrics; in class Landroid/view/WindowManager; or its super classes (declaration of 'android.view.WindowManager' appears in /system/framework/framework.jar!classes3.dex)
        at com.android.launcher3.util.window.WindowManagerProxy.getRealBounds(WindowManagerProxy.java:131)
        at com.android.launcher3.util.DisplayController$Info.<init>(DisplayController.java:327)
        at com.android.launcher3.util.DisplayController.<init>(DisplayController.java:120)
        at com.android.launcher3.util.DisplayController.$r8$lambda$QjdXHmv721WSoJW-MI-3oZlD7FY(Unknown Source:2)
        at com.android.launcher3.util.DisplayController$$ExternalSyntheticLambda0.get(Unknown Source:0)
        at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0$com-android-launcher3-util-MainThreadInitializedObject(MainThreadInitializedObject.java:58)
        at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda2.get(Unknown Source:4)
        at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:84)
        at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:57)
        at com.android.launcher3.InvariantDeviceProfile.initGrid(InvariantDeviceProfile.java:311)
        at com.android.launcher3.InvariantDeviceProfile.<init>(InvariantDeviceProfile.java:195)
        at com.android.launcher3.InvariantDeviceProfile.$r8$lambda$DNcXzmawjoq65q3wgQi9M48DryY(Unknown Source:2)
        at com.android.launcher3.InvariantDeviceProfile$$ExternalSyntheticLambda1.get(Unknown Source:0)
        at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0$com-android-launcher3-util-MainThreadInitializedObject(MainThreadInitializedObject.java:58)
        at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda2.get(Unknown Source:4)
        at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:84)
        at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:57)
        at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:143)
        at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:84)
        at com.android.launcher3.LauncherAppState$$ExternalSyntheticLambda4.get(Unknown Source:2)
        at com.android.launcher3.util.MainThreadInitializedObject.lambda$get$0$com-android-launcher3-util-MainThreadInitializedObject(MainThreadInitializedObject.java:58)
        at com.android.launcher3.util.MainThreadInitializedObject$$ExternalSyntheticLambda2.get(Unknown Source:4)
        at com.android.launcher3.util.TraceHelper.allowIpcs(TraceHelper.java:84)
        at com.android.launcher3.util.MainThreadInitializedObject.get(MainThreadInitializedObject.java:57)
        at com.android.launcher3.LauncherAppState.getInstance(LauncherAppState.java:72)
        at com.android.launcher3.Launcher.onCreate(Launcher.java:456)
        at android.app.Activity.performCreate(Activity.java:7869)

**Comment by yuchuangu85** [comment]
@hjqiaho 这个还没有跑通，因为最近太忙，还没有时间搞。

**Comment by yuchuangu85** [comment]
@hjqiaho 由于还没有找到对应的依赖包，现在只能编译withoutquickstep的模式

**Comment by hjqiaho** [comment]
@yuchuangu85   编译的是withoutquickstep   我看网上的说法WindowMetrics只能用再android13的设备上，你那边的测试设备系统是多少的 ，我这android10的报错

**Comment by yuchuangu85** [comment]
@hjqiaho 我用的Android10，现在也正在测试哪些有问题，谷歌没有往下兼容，需要自己处理。

**Comment by yuchuangu85** [comment]
@hjqiaho 很多API都是30以上的。
